llm:
  aliqwen:
    api-key: ${ALI_QWEN_API:}   # 从环境变量 ALI_QWEN_API 读取，或者直接写死
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model-name: qwen-plus
  deepseek:
    api-key: ${SICHENG_DEEPSEEK_API:}
    base-url: https://api.deepseek.com/v1
    model-name: deepseek-chat